before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: y79oA2xqPjT7jXjN805+1rQu5Y4tpk/DsxhjUj0FtWtILVp+6e/00VZpFWr5wVrBYugDQbzlM02wdEkX1vwtzwLgUkj7ZlNhUqrSQ3KXUc9zXcHik9O99PIT/aSNPGgBEqySQ1Cov0nFmpic7IjrMWQESRyww/A0mNR1bkmn4XK/fIaVv+STABa/jufjBUJm0o94BxylWslSi+y+EFh/x75kio6V+1L/CIhW7zNz8j4AqtA+ZdjCV8AF7RUUcT3GoKIDvQJPqi3a7+B+dRQwDZff+aeMw4VHTrLKifdRfgaLiUYlLzhFswP7K+d2/Rbv3dFQ7hT570+qEamJ4IwRkToZ64yUX9iw4NdrCfgPBEkzTd0vS19V1+Ucm/Mt+ryweV8MR6vigNk+ggv7ma72m8FFN3uFqL5fCvJSh9ValwvP8vwePL8+HQ5V8eFLR4pmVhr45qGyyPNIN+TEPQqCwEC2GrGKd5gN6PDqFy3qiW0L5hEW5FEgzhnca2MsgnMHx2Rxd0HGQgtcrfObxl7j3wQn8co3sZkv+6t5YnGFSjp/Qxuh5/XNc4j2ya1L0fi3GeK/9qSEtzP5CO96cje9ghAzGGiTEHypNHz6JsfSZFBVQx+RhfJGRDZjKJCVXA+1L81GDwrgbg/h93n0eL1JokK8v10zbnqgYHvfEkKU0Ts= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
